# gs_videoReport Demo Configuration
# This is for testing the CLI framework without a real API key

# Google Gemini API Configuration
google_api:
  api_key: "AIzaSyCr_yrD6Dkcgx4VdNQA-awnBkzPg0SNVJI"  # Your actual API key
  model: "gemini-2.5-flash"
  temperature: 0.7
  max_tokens: 8192
  max_file_size_mb: 100
  processing_timeout_seconds: 300

# Template Configuration
templates:
  default_template: "comprehensive_lesson"
  template_path: "src/gs_video_report/templates/prompts"
  
# Output Configuration  
output:
  default_path: "./output"
  file_naming: "{video_title}_{timestamp}"
  include_metadata: true

# Processing Configuration
processing:
  verbose: true
  retry_attempts: 3
  timeout_seconds: 300

# Video Processing
video:
  max_duration_minutes: 60
  download_quality: "best"
  supported_formats: [".mp4", ".mov", ".avi", ".mkv", ".webm", ".m4v"]
