# yaml-language-server: $schema=./schemas/config.schema.json
# gs_videoReport 配置文件
# 注意：此文件将被 .gitignore 忽略，请勿提交到版本控制

# ===== 基础配置 =====
api_key: "YOUR_GEMINI_API_KEY_HERE"  # 从 https://makersuite.google.com/app/apikey 获取
model_name: "gemini-2.5-flash"
default_output_path: "./output/"
default_prompt_template: "comprehensive_lesson"

# ===== 认证配置 =====
auth_type: "api_key"

# OAuth 2.0 配置（用于访问私有YouTube视频）
# 如需访问私有视频，请在 Google Cloud Console 中创建OAuth 2.0客户端ID
# oauth:
#   client_id: "your-google-oauth-client-id"
#   client_secret: "your-google-oauth-client-secret"

# ===== 高级配置 =====
# 视频处理配置
video_processing:
  max_file_size_mb: 100
  supported_formats: ["mp4", "mov", "avi", "mkv", "webm", "m4v"]
  upload_timeout_seconds: 300

# API调用配置
api_config:
  max_retries: 3
  timeout_seconds: 300
  temperature: 0.7
  max_output_tokens: 8192

# 输出配置
output_config:
  include_timestamps: true
  timestamp_format: "youtube"
  obsidian_compatibility: true
  
# 错误处理配置  
error_handling:
  auto_retry_on_network_error: true
  show_detailed_errors: false
  log_api_calls: false
