# Test Configuration for YouTube Video Analysis v2
# 修正格式的测试配置文件，符合config.py的期望格式

# Google API Configuration - 符合代码期望的格式
google_api:
  api_key: "AIzaSyCr_yrD6Dkcgx4VdNQA-awnBkzPg0SNVJI"  # 测试API密钥
  model: "gemini-2.5-flash"  # 使用最新模型支持视频分析
  temperature: 0.3  # 降低温度以获得更稳定的转录结果
  max_tokens: 8192
  max_file_size_mb: 100
  processing_timeout_seconds: 600  # 增加超时时间以处理长视频

# Template Configuration
templates:
  default_template: "chinese_transcript"  # 使用中文转录模板
  template_path: "src/gs_video_report/templates/prompts"
  
# Output Configuration  
output:
  directory: "./test_output"  # 测试输出目录
  template_directory: "src/gs_video_report/templates/outputs"
  file_naming: "{video_title}_{timestamp}"
  include_metadata: true
  create_backup: true
  max_file_size_mb: 50
  encoding: "utf-8"
  default_path: "./test_output"

# Processing Configuration
processing:
  verbose: true  # 启用详细输出用于测试
  retry_attempts: 3
  timeout_seconds: 600  # 增加超时时间

# Video Processing
video:
  max_duration_minutes: 120  # 允许更长的视频
  download_quality: "best"
  supported_formats: [".mp4", ".mov", ".avi", ".mkv", ".webm", ".m4v"]

# Test-specific Configuration
test:
  public_video_url: "https://www.youtube.com/watch?v=7r7ZDugy3EE"
  private_video_url: "https://www.youtube.com/watch?v=EXmz9O1xQbM"
  expected_output_format: "chinese_transcript"
  test_timeout_minutes: 15

# Error Scenarios Configuration - 用于错误测试
error_test_configs:
  invalid_api_key:
    google_api:
      api_key: "invalid_key_for_testing"
      model: "gemini-2.5-flash"
  
  missing_api_key:
    google_api:
      api_key: ""
      model: "gemini-2.5-flash"
      
  invalid_model:
    google_api:
      api_key: "AIzaSyCr_yrD6Dkcgx4VdNQA-awnBkzPg0SNVJI"
      model: "invalid-model-name"

# Performance Testing Configuration  
performance_test:
  memory_monitoring: true
  time_tracking: true
  api_call_logging: true
  benchmark_videos:
    short: 
      max_duration: 5  # 5分钟以下
      expected_processing_time: 120  # 2分钟
    medium:
      max_duration: 20  # 5-20分钟
      expected_processing_time: 600  # 10分钟  
    long:
      max_duration: 60  # 20-60分钟
      expected_processing_time: 1800  # 30分钟
